{"name":"auto_ml/auto_ml.nickmazz403/attachments/referenced_auto_ml.nickmazz403","body":"{\"version\":2,\"trainingGuid\":\"40816caf-600d-4cee-bf40-af7f364d2942\",\"message\":{\"level\":\"info\",\"text\":\"Node automl: ERROR: ingesting data Cannot connect to: data asset\\nReason: Error: Not Found\"},\"state\":\"failed\",\"pipelines\":{},\"estimators\":{},\"last_modified\":1634053906248,\"preprocessing_step\":\"AUTO_AI_STEP_BUILDING_PIPELINES\",\"created_at\":\"2021-10-12T15:46:28.264Z\",\"message_log\":[{\"timestamp\":1634053599282,\"text\":\"Train_log_msg_starting\",\"running_pipeline\":\"\",\"level\":\"info\"},{\"timestamp\":1634053614345,\"level\":\"info\",\"text\":\"Node automl: ERROR: ingesting data Cannot connect to: data asset\\nReason: Error: Not Found\"}],\"completed_at\":\"2021-10-12T15:46:54.327Z\",\"failure\":{\"trace\":\"na\",\"errors\":[{\"code\":\"autoai_error\",\"message\":\"ERROR: ingesting data Cannot connect to: data asset\\nReason: Error: Not Found\"}]}}"}